/*
 This file contains functions for handling the legend, including the template and source used.
*/

export function r2dtLegend(template, source) {
    const getSourceLink = (src) => {
        const db = src?.toLowerCase();
        if (db === 'crw') return `<a href="https://crw2-comparative-rna-web.org/" target="_blank">CRW</a>`;
        if (db === 'rfam') return `<a href="https://rfam.org/" target="_blank">Rfam</a>`;
        if (db === 'ribovision') return `<a href="http://apollo.chemistry.gatech.edu/RiboVision/" target="_blank">RiboVision</a>`;
        if (db === 'gtrnadb') return `<a href="http://gtrnadb.ucsc.edu/" target="_blank">GtRNAdb</a>`;
        return src || '';
    };

    const sentence = (!template || !source)
        ? `Generated by <a href="https://r2dt.bio" target="_blank">R2DT</a>. <a href="https://rnacentral.org/help/secondary-structure" target="_blank">Learn more →</a>`
        : template === 'R2R'
            ? `Generated by <a href="https://r2dt.bio" target="_blank">R2DT</a> using the <i>${template}</i> software. <a href="https://rnacentral.org/help/secondary-structure" target="_blank">Learn more →</a>`
            : `Generated by <a href="https://r2dt.bio" target="_blank">R2DT</a> using the <i>${template}</i> template provided by ${getSourceLink(source)}. <a href="https://rnacentral.org/help/secondary-structure" target="_blank">Learn more →</a>`;

    return `
        <div class="r2dt-card">
            <div class="r2dt-card-header"><strong>Legend</strong></div>
            <div class="r2dt-card-body">
                <span class="r2dt-source-template-text">${sentence}</span>
                <ul class="r2dt-list-unstyled">
                    <li class="r2dt-mt-1"><span class="r2dt-traveler-black r2dt-traveler-key"></span> Same as the template</li>
                    <li class="r2dt-mt-1"><span class="r2dt-traveler-green r2dt-traveler-key"></span> Modified compared to the template</li>
                    <li class="r2dt-mt-1"><span class="r2dt-traveler-magenta r2dt-traveler-key"></span> Inserted nucleotides</li>
                    <li class="r2dt-mt-1"><span class="r2dt-traveler-blue r2dt-traveler-key"></span> Repositioned compared to the template</li>
                    <li class="r2dt-mt-2"><strong>Tip:</strong> Hover over nucleotides for more details</li>
                </ul>
            </div>
        </div>
    `;
}
